# Generated by Django 3.2.8 on 2023-01-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('incidentDept', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incidentLoc', models.TextField()),
                ('initialSeverity', models.CharField(max_length=60)),
                ('cause', models.TextField()),
                ('actionTaken', models.TextField()),
                ('envInc', models.BooleanField(default=False)),
                ('injury', models.BooleanField(default=False)),
                ('properties', models.BooleanField(default=False)),
                ('Vehical', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
